-- ============================================================================
-- Migration 001: Telemetry System Schema
-- ============================================================================
-- Creates tables for F1 25 telemetry data capture and storage.
-- Schema supports:
-- - Sessions (container for laps and setups)
-- - Lap metadata (lap times, validity, associations)
-- - Lap telemetry samples (detailed position/velocity/input data)
-- - Car setup snapshots (complete car configuration)
--
-- Design principles:
-- - Foreign key enforcement with CASCADE/SET NULL for referential integrity
-- - Indexed columns for query performance (track_id, lap_distance, etc.)
-- - Schema versioning for forward compatibility
-- - UTC timestamps for consistent time handling
-- ============================================================================

-- Enable foreign key constraints (SQLite default: OFF)
PRAGMA foreign_keys = ON;

-- ============================================================================
-- Table: sessions
-- ============================================================================
-- Container for F1 25 gameplay sessions. Each session represents a single
-- Time Trial run, Practice session, etc. Sessions link to laps and setups.
-- ============================================================================
CREATE TABLE IF NOT EXISTS sessions (
    -- Primary key: F1 25 session UID from PacketHeader.m_sessionUID
    session_uid INTEGER PRIMARY KEY NOT NULL,
    
    -- Track identifier from F1 25 (e.g., "monaco", "silverstone")
    track_id TEXT NOT NULL,
    
    -- Session type from F1 25 PacketSessionData.m_sessionType
    -- Examples: 18 = Time Trial, 5 = Practice, etc.
    session_type INTEGER NOT NULL,
    
    -- Schema version for future compatibility (current: 1)
    schema_version INTEGER NOT NULL DEFAULT 1,
    
    -- Session start timestamp (UTC)
    created_at TEXT NOT NULL DEFAULT (datetime('now', 'utc'))
);

-- Index for track-based queries (e.g., "show all Monaco sessions")
CREATE INDEX IF NOT EXISTS idx_sessions_track 
    ON sessions(track_id);

-- Index for chronological queries (e.g., "most recent sessions")
CREATE INDEX IF NOT EXISTS idx_sessions_created 
    ON sessions(created_at DESC);


-- ============================================================================
-- Table: car_setups
-- ============================================================================
-- Car setup snapshots from F1 25 PacketCarSetupData. Each snapshot captures
-- complete car configuration (23 parameters) at a specific moment. Setups
-- can be associated with multiple laps.
-- ============================================================================
CREATE TABLE IF NOT EXISTS car_setups (
    -- Primary key: UUID generated by application
    setup_id TEXT PRIMARY KEY NOT NULL,
    
    -- Foreign key: session this setup was captured in
    session_uid INTEGER NOT NULL,
    
    -- Session time when snapshot was captured (milliseconds)
    timestamp_ms INTEGER NOT NULL,
    
    -- Aerodynamics
    front_wing INTEGER NOT NULL,
    rear_wing INTEGER NOT NULL,
    
    -- Differential
    on_throttle INTEGER NOT NULL,
    off_throttle INTEGER NOT NULL,
    
    -- Camber & Toe
    front_camber REAL NOT NULL,
    rear_camber REAL NOT NULL,
    front_toe REAL NOT NULL,
    rear_toe REAL NOT NULL,
    
    -- Suspension
    front_suspension INTEGER NOT NULL,
    rear_suspension INTEGER NOT NULL,
    front_anti_roll_bar INTEGER NOT NULL,
    rear_anti_roll_bar INTEGER NOT NULL,
    front_suspension_height INTEGER NOT NULL,
    rear_suspension_height INTEGER NOT NULL,
    
    -- Brakes
    brake_pressure INTEGER NOT NULL,
    brake_bias INTEGER NOT NULL,
    engine_braking INTEGER NOT NULL,
    
    -- Tyres (PSI)
    front_left_tyre_pressure REAL NOT NULL,
    front_right_tyre_pressure REAL NOT NULL,
    rear_left_tyre_pressure REAL NOT NULL,
    rear_right_tyre_pressure REAL NOT NULL,
    
    -- Weight
    ballast INTEGER NOT NULL,
    fuel_load REAL NOT NULL,
    
    -- Schema version for future compatibility
    setup_schema_version INTEGER NOT NULL DEFAULT 1,
    
    -- Creation timestamp (UTC)
    created_at TEXT NOT NULL DEFAULT (datetime('now', 'utc')),
    
    -- Foreign key constraint: setup belongs to session
    -- ON DELETE CASCADE: if session deleted, delete associated setups
    FOREIGN KEY (session_uid) 
        REFERENCES sessions(session_uid) 
        ON DELETE CASCADE
);

-- Index for session-based queries (e.g., "all setups in session")
CREATE INDEX IF NOT EXISTS idx_setups_session 
    ON car_setups(session_uid);


-- ============================================================================
-- Table: lap_metadata
-- ============================================================================
-- Lap metadata and summary data. Each row represents one lap in a session.
-- Contains lap time, validity, track/session associations, and optional
-- car setup reference.
-- ============================================================================
CREATE TABLE IF NOT EXISTS lap_metadata (
    -- Primary key: UUID generated by application (trace_id)
    trace_id TEXT PRIMARY KEY NOT NULL,
    
    -- Foreign key: session this lap belongs to
    session_uid INTEGER NOT NULL,
    
    -- Foreign key: car setup used for this lap (optional)
    -- NULL if no setup snapshot associated with this lap
    setup_id TEXT,
    
    -- Track identifier (denormalized from session for query performance)
    track_id TEXT NOT NULL,
    
    -- Lap number within session (1-based)
    lap_number INTEGER NOT NULL,
    
    -- Player car index from F1 25 (0-21)
    car_index INTEGER NOT NULL,
    
    -- Final lap time in milliseconds (NULL if lap incomplete)
    lap_time_ms INTEGER,
    
    -- Lap validity flag (false if penalties, corner cutting, etc.)
    is_valid INTEGER NOT NULL DEFAULT 1,
    
    -- Creation timestamp (UTC)
    created_at TEXT NOT NULL DEFAULT (datetime('now', 'utc')),
    
    -- Foreign key constraints
    -- ON DELETE CASCADE: if session deleted, delete all its laps
    FOREIGN KEY (session_uid) 
        REFERENCES sessions(session_uid) 
        ON DELETE CASCADE,
    
    -- ON DELETE SET NULL: if setup deleted, lap metadata remains but setup_id becomes NULL
    FOREIGN KEY (setup_id) 
        REFERENCES car_setups(setup_id) 
        ON DELETE SET NULL
);

-- Index for session-based queries (e.g., "all laps in session")
CREATE INDEX IF NOT EXISTS idx_lap_meta_session 
    ON lap_metadata(session_uid);

-- Index for track-based queries (e.g., "all laps on Monaco")
CREATE INDEX IF NOT EXISTS idx_lap_meta_track 
    ON lap_metadata(track_id);

-- Index for filtering valid laps (e.g., "fastest valid lap")
CREATE INDEX IF NOT EXISTS idx_lap_meta_valid 
    ON lap_metadata(is_valid, lap_time_ms);


-- ============================================================================
-- Table: lap_telemetry
-- ============================================================================
-- Detailed telemetry samples for each lap. Each row is a single TelemetrySample
-- captured from F1 25 UDP packets. Samples are chronologically ordered within
-- each lap trace.
--
-- NOTE: This table will grow rapidly (typically 300-500 samples per lap).
-- Indexes on trace_id and lap_distance are critical for query performance.
-- ============================================================================
CREATE TABLE IF NOT EXISTS lap_telemetry (
    -- Foreign key: lap this sample belongs to
    trace_id TEXT NOT NULL,
    
    -- Timestamp in session time (milliseconds)
    timestamp_ms INTEGER NOT NULL,
    
    -- Lap distance in meters (for spatial queries)
    lap_distance REAL NOT NULL,
    
    -- Position (world space, meters)
    world_position_x REAL NOT NULL,
    world_position_y REAL NOT NULL,
    world_position_z REAL NOT NULL,
    
    -- Velocity (world space, m/s)
    world_velocity_x REAL NOT NULL,
    world_velocity_y REAL NOT NULL,
    world_velocity_z REAL NOT NULL,
    
    -- G-forces
    g_force_lateral REAL NOT NULL,
    g_force_longitudinal REAL NOT NULL,
    
    -- Orientation
    yaw REAL NOT NULL,
    
    -- Car telemetry
    speed REAL NOT NULL,
    throttle REAL NOT NULL,
    steer REAL NOT NULL,
    brake REAL NOT NULL,
    gear INTEGER NOT NULL,
    engine_rpm INTEGER NOT NULL,
    drs INTEGER NOT NULL,
    
    -- Lap metadata
    lap_number INTEGER NOT NULL,
    
    -- Foreign key constraint
    -- ON DELETE CASCADE: if lap deleted, delete all its telemetry samples
    FOREIGN KEY (trace_id) 
        REFERENCES lap_metadata(trace_id) 
        ON DELETE CASCADE
);

-- Index for trace-based queries (e.g., "all samples for lap X")
-- CRITICAL for performance: each lap query must filter by trace_id
CREATE INDEX IF NOT EXISTS idx_telemetry_trace 
    ON lap_telemetry(trace_id);

-- Index for distance-based queries (e.g., "samples between 1000m-2000m")
-- Enables efficient spatial analysis (sector times, corner analysis, etc.)
CREATE INDEX IF NOT EXISTS idx_telemetry_lap_distance 
    ON lap_telemetry(trace_id, lap_distance);


-- ============================================================================
-- Migration Metadata
-- ============================================================================
-- Schema version tracking for migration system
-- ============================================================================
CREATE TABLE IF NOT EXISTS schema_migrations (
    version INTEGER PRIMARY KEY NOT NULL,
    applied_at TEXT NOT NULL DEFAULT (datetime('now', 'utc'))
);

-- Record this migration
INSERT OR IGNORE INTO schema_migrations (version) VALUES (1);
